    
[package]
name = "comandU"
version = "1.0.0"
authors = ["Tu Nombre <tuemail@example.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
colored = "2.0"
dirs = "5.0"
toml = "0.5"

[features]
default = []

